### ISSUE TITLE
Support latest Node LTS (20)

### ISSUE THREAD

**Issue by JakobLierman** [Palmabit-IT/strapi-app-version#3]
Installing this with Node 20 results in the following error:
`error @palmabit/strapi-app-version@1.1.0: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=18.x.x". Got "20.9.0"`

Make sure to support the latest Node LTS versions: `"^18 || ^20"`.

**Comment by royanon** [comment]
PR https://github.com/Palmabit-IT/strapi-app-version/pull/4

**Comment by JakobLierman** [comment]
Fixed: https://github.com/Palmabit-IT/strapi-app-version/commit/b4f8fa5b465df4898edc8d5309bb403acd0076e8
